### ISSUE TITLE
Port to libSass

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1916]
This issue will track the top level tasks that are required for Compass to be ported to libSass. When this issue is closed, we will release Compass 2.0.
# Vision

Compass 2.0 will not use ruby and will run libSass for compilation by default. However, It will allow you to opt-in to using ruby sass.
## TODO
- [ ] `libcompass` - a C++ library that can be used to compile a Sass file in a Compass-compatible Sass environment.
- [ ] `compass` compiled binaries for mac, linux, and windows that implements a large subset of the commands supported by the ruby compass command including a watcher and sprite generator.
- [ ] ruby ecosystem - Most compass extensions do not need to use ruby for much more than to self-register themselves. However, some do use ruby to define Sass functions. Obviously, this won't work going forward as it is implementation specific and it is not feasible to embed a ruby interpreter into libsass as most extensions expect not just a ruby language, but the ruby sass implementation specifics to be present. I think Lua may be a better language to allow Sass extensions in. It is trivial to embed a lua interpreter in both ruby and c++ and to creating bidirectional bindings of the public API that we want to expose to that environment.
- [ ] New config format. Either Sass introduces an extensible config format or compass creates one that is portable between both ruby and libsass. (probably start with compass and then if we like what we make, migrate that to sass as a standard. See: https://github.com/sass/sass/issues/1155)
- [ ] Decide if compass 2.0 should be written in Rust instead of C++ and simply use rust/c bindings to call out to libSass.
- [ ] Ensure that libSass is feature compatible with the features compass uses or dumb compass down to make it so. Especially around the importer architecture which in libsass seems to assume sass files on disk.
- [ ] Installer & upgrader - get updates to the binaries as well as the sass files and caniuse data.

**Comment by micahgodbolt** [comment]
Wow! Awesome! :D

**Comment by chriseppstein** [comment]
Please let's keep the comments on this issue on-topic. I appreciate the enthusiasm, but I need this to be a useful issue that can be used to discuss the work and track the issues so I will delete any `+1` or other such comments that are intended to voice support or excitement. Feel free to send me a tweet if you need to emote as such.

**Comment by KittyGiraudel** [comment]
I will not be able to help with C or Rust, but once you have a working skeleton, you can count on me for extensive testing.

**Comment by imathis** [comment]
:boom: :bangbang: :boom:

**Comment by saschaeggi** [comment]
Ping me if you need testers for this! This is huge! :)

**Comment by ritcheyer** [comment]
@chriseppstein This is fantastic news and would make many a Frontend Developer's Day! :smile: I know the nature of OSS timetables are…flexible but wondering if you have any ideas for when this may be completed?

(in light of your first comment, feel free to delete this)

**Comment by chriseppstein** [comment]
Sorry, no dates at this time.

**Comment by xzyfer** [comment]
I'm happy to lend any help I can in regards to Libsass. I'm also happy to contribute to compass c/rust side of things.

**Comment by moneal** [comment]
I'm so happy about this, I'm dancing in my seat. I've had to spend way too much time to get little image functions to work without compass.

**Comment by chriseppstein** [comment]
An alternative approach would be to port Compass to Javascript and target only node-sass. This is less generally re-usable but it would make compass easier to contribute to. I'm still leaning towards having a core for compass that is statically compiled.

**Comment by chriseppstein** [comment]
I researched it and it turns out to not be that hard to embed resources like the sass files into a compiled binary. But it will require a custom importer to extract them from the executable without unpacking them -- though we will still need to provide a `compass unpack compass` like we do now which will put the compass stylesheets onto disk.

**Comment by lolmaus** [comment]
It would be too good if nobody were unhappy about this, right?

As a happy Ruby user, i'm very concerned with what will happen to Ruby Compass. The matter is that Compass is an umbrella term for a number of entities:
- A library of handy Sass mixins and functions.
- A standard for organizing Sass code in a project and a correpsonding configuration file.
- A command-line tool to create, compile and enhance projects.
- A standard for bundling Sass extensions.
- An ecosystem of those extensions and an effortless way to import them.
- A mean of effortlessly enhancing vanilla Sass functionality with custom behavior.

After you migrate Compass off Ruby, what will be left of that?

**Comment by chriseppstein** [comment]
The only aspect of compass here that will be called into question is:

> A mean of effortlessly enhancing vanilla Sass functionality with custom behavior.

If by "effortlessly" you mean to ruby users using ruby code then that aspect will cease to exist. I hope to find a way for the "sass language" provide a standard mechanism for extensions that can be used in different implementations. I have started a conversation about this here: https://github.com/sass/sass/issues/1608

**Comment by scottdavis** [comment]
we could even consider something like mruby: https://github.com/mruby/mruby

**Comment by klojniewski** [comment]
+1

**Comment by saschaeggi** [comment]
What's the status here @chriseppstein ?

**Comment by saper** [comment]
I'd vote for a simple C instead of C++/Rust/whatever. libsass does not require the client to be written in C.

**Comment by scottdavis** [comment]
Im pretty sure we have transitioned away from this and are setting up suport for a compass like system on node-sass (libsass or node) using the https://github.com/sass-eyeglass/eyeglass project.

**Comment by Zauberfisch** [comment]
@scottdavis you/they/we are? that's bad news, at least for me :S
not that I am per se against node, but swapping ruby out for javascript doesn't sound like a good idea to me. We would just trade people complaining about having to install ruby for people complaining about having to install node+npm.
Obviously the performance gains are the main factor, and I see the argument of ease of contribution, but I think having binary of compass is quiet a big thing as well.

I have actually migrated systems away from compass, just because I can deploy libsass easily to my server infrastructure.

**Comment by lolmaus** [comment]
Node/npm are a standard for web development. I can't imagine a modern web site/app developed without the use of Node.

**Comment by Zauberfisch** [comment]
I can.
While I do have node installed, and use npm and bower, I have projects where I successfully avoided using those.
It is obviously often a trade-off, but to me, avoiding unnecessary dependencies where I can is an important issue.

**Comment by chriseppstein** [comment]
A much higher percentage of Sass users know javascript than know ruby. As a result javascript is a vibrant ecosystem for front end tool development. In most user's stacks, node has become a must-have for front end tooling. Ruby sticks out in these applications like a sore thumb. The plan stated above made Compass even more inaccessible to our users because even fewer developers know C/C++, but eyeglass makes the core features of compass available in a much more accessible way which means our users can contribute to development and that's a huge win.

I know not everyone will be happy about this. There's nothing I can do about that. This is progress and a big win for the Sass community at large.

**Comment by acusti** [comment]
That’s exciting! It will very much simplify my readme files that I write with instructions for developers how to get the development toolchains up and running, and the issues those developers are then likely to run into it.

For those of us who subscribed to this issue to know when we will be able to use Compass + libsass, is their another issue we could follow to get updated on the migration to node-sass (and the resulting compatibility with libsass)? Or is the Compass functionality only going to be installable as smaller NPM modules and no longer be recognizable as its current form?

**Comment by chriseppstein** [comment]
@acusti It is my goal that most compass projects could be ported to eyeglass with only minimal changes. What I'd like to see is an eyeglass-compass-compat module that provides a shim for compass-based stylesheets.

In the javascript world, autoprefixer is a better solution than the css3 module, so there's currently no plan to port the css3 module to eyeglass, though obviously it is something that could be done by a member of the community.

**Comment by lolmaus** [comment]
I've been using Autoprefixer with Ruby Compass first from npm, then from RubyGems. :P

**Comment by alanhogan** [comment]
Hey Chris,

Appreciate all  the thought that went into here and think the resolution is a sound one.

Just a little note — you may want to consider editing the description on this issue, as a quick read gives the impression Compass 2.0 with lib-sass support was released, and this is a top search result for “compass lib-sass.”

![screen shot 2015-07-13 at 11 25 03 am](https://cloud.githubusercontent.com/assets/6808/8657375/19ba86d4-2952-11e5-94f2-2bb5c3cc0210.png)

Cheers.
